
;---------------------------------------------------------------------       
	.export		_cs8900a_rxtxreg
	.export		_cs8900a_txcmd
	.export		_cs8900a_txlen
	.export		_cs8900a_packetpp
	.export		_cs8900a_ppdata
	

;---------------------------------------------------------------------

	_cs8900a_rxtxreg	= $c0a0
	_cs8900a_txcmd		= $c0a4
	_cs8900a_txlen		= $c0a6
	_cs8900a_packetpp	= $c0aa
	_cs8900a_ppdata		= $c0ac

