ulcornerpattern:	.byte $ff,$ff,$c0,$cf,$c0,$c3,$c0,$c0
titlebarpattern:	.byte $ff,$ff,$00,$ff,$00,$ff,$00,$00
urcornerpattern:	.byte $ff,$fc,$00,$f0,$00,$c0,$00,$00
lborderpattern:		.byte $c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0
rborderpattern:		.byte $0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b
lrcornerpattern:	.byte $0b,$0b,$0b,$0b,$fb,$03,$ff,$ff
llcornerpattern:	.byte $c0,$c0,$c0,$c0,$c0,$c0,$80,$00

buttonleftpattern:	.byte $c5,$df,$df,$df,$df,$df,$df,$df	
buttonrightpattern:	.byte $fb,$fb,$fb,$fb,$fb,$fb,$fb,$a3
