ulcornerpattern:	.byte $fe,$f8,$e0,$c0,$c0,$80,$80,$00
titlebarpattern:	.byte $00,$55,$aa,$00,$aa,$00,$00,$00
urcornerpattern:	.byte $7f,$1f,$07,$03,$03,$01,$01,$00

lborderpattern:		.byte $00,$00,$00,$00,$00,$00,$00,$00
rborderpattern:		.byte $00,$00,$00,$00,$00,$00,$00,$00  
	
lrcornerpattern:	.byte $00,$01,$01,$03,$03,$07,$1f,$7f
llcornerpattern:	.byte $00,$80,$80,$c0,$c0,$e0,$f8,$fe

buttonleftpattern:	.byte $03,$0f,$1f,$1f,$1f,$1f,$0f,$03
buttonrightpattern:	.byte $c0,$f0,$f8,$f8,$f8,$f8,$f0,$c0
